-- Generated by scripts/emit-bootstrap-sql.mjs from prisma/schema.prisma.
-- Do not edit: rebuild instead. Applied by src/bootstrap.ts the first time an
-- empty SQLite store is opened.

-- CreateTable
CREATE TABLE IF NOT EXISTS "users" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "email" TEXT,
    "passwordHash" TEXT,
    "displayName" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "walletAddress" TEXT,
    "walletLinkedAt" DATETIME,
    "walletProvenAt" DATETIME,
    "walletProvenAddress" TEXT
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "spent_siwe_nonces" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "nonceHash" TEXT NOT NULL,
    "expiresAt" DATETIME NOT NULL,
    "spentAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "workspaces" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "ownerId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "contextLimit" INTEGER NOT NULL DEFAULT 6000,
    "modelSummariesEnabled" BOOLEAN NOT NULL DEFAULT false,
    "modelSummariesEnabledAt" DATETIME,
    "modelSummariesEnabledBy" TEXT,
    "modelProvider" TEXT NOT NULL DEFAULT 'openrouter',
    "modelName" TEXT NOT NULL DEFAULT 'anthropic/claude-haiku-4.5',
    "usageProvider" TEXT NOT NULL DEFAULT 'openrouter',
    "usageKeyCipher" TEXT,
    "usageKeyHint" TEXT NOT NULL DEFAULT '',
    "usageLinkedAt" DATETIME,
    CONSTRAINT "workspaces_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "agents" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "kind" TEXT NOT NULL DEFAULT 'subagent',
    "description" TEXT NOT NULL DEFAULT '',
    "keyHash" TEXT NOT NULL,
    "keyPrefix" TEXT NOT NULL,
    "canRead" BOOLEAN NOT NULL DEFAULT true,
    "canWrite" BOOLEAN NOT NULL DEFAULT true,
    "canImport" BOOLEAN NOT NULL DEFAULT false,
    "canMerge" BOOLEAN NOT NULL DEFAULT true,
    "canResolve" BOOLEAN NOT NULL DEFAULT false,
    "canForget" BOOLEAN NOT NULL DEFAULT false,
    "canExport" BOOLEAN NOT NULL DEFAULT false,
    "revokedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastSeenAt" DATETIME,
    CONSTRAINT "agents_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "memory_records" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "recordId" TEXT NOT NULL,
    "version" INTEGER NOT NULL DEFAULT 1,
    "workspaceId" TEXT NOT NULL,
    "agentId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "topic" TEXT NOT NULL,
    "source" TEXT NOT NULL DEFAULT '',
    "claimedAuthor" TEXT,
    "scope" TEXT NOT NULL DEFAULT 'workspace',
    "factKey" TEXT,
    "factValue" TEXT,
    "factContext" TEXT NOT NULL DEFAULT '',
    "contentHash" TEXT NOT NULL,
    "isCurrent" BOOLEAN NOT NULL DEFAULT true,
    "previousVersionId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" DATETIME,
    "deletedBy" TEXT,
    "purged" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "memory_records_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "memory_records_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "agents" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "record_links" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "fromRecordId" TEXT NOT NULL,
    "toRecordId" TEXT NOT NULL,
    "note" TEXT NOT NULL DEFAULT '',
    "createdByAgentId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "record_links_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "record_links_fromRecordId_fkey" FOREIGN KEY ("fromRecordId") REFERENCES "memory_records" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "record_links_toRecordId_fkey" FOREIGN KEY ("toRecordId") REFERENCES "memory_records" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "record_links_createdByAgentId_fkey" FOREIGN KEY ("createdByAgentId") REFERENCES "agents" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "merged_blocks" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "scope" TEXT NOT NULL DEFAULT 'workspace',
    "ownerAgentId" TEXT,
    "topic" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "origin" TEXT NOT NULL DEFAULT 'deterministic',
    "modelName" TEXT,
    "summary" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "rebuiltAt" DATETIME,
    "staleAt" DATETIME,
    "staleReason" TEXT,
    CONSTRAINT "merged_blocks_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "merged_block_sources" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "blockId" TEXT NOT NULL,
    "recordRowId" TEXT NOT NULL,
    "recordId" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    CONSTRAINT "merged_block_sources_blockId_fkey" FOREIGN KEY ("blockId") REFERENCES "merged_blocks" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "merged_block_sources_recordRowId_fkey" FOREIGN KEY ("recordRowId") REFERENCES "memory_records" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "conflicts" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "scope" TEXT NOT NULL DEFAULT 'workspace',
    "factKey" TEXT NOT NULL,
    "factContext" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'open',
    "detectedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "resolvedRecordId" TEXT,
    "resolvedVersion" INTEGER,
    "rationale" TEXT,
    "resolvedByUserId" TEXT,
    "resolvedByAgentId" TEXT,
    "resolvedAt" DATETIME,
    CONSTRAINT "conflicts_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "conflicts_resolvedByUserId_fkey" FOREIGN KEY ("resolvedByUserId") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "conflicts_resolvedByAgentId_fkey" FOREIGN KEY ("resolvedByAgentId") REFERENCES "agents" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "conflict_sides" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "conflictId" TEXT NOT NULL,
    "recordRowId" TEXT NOT NULL,
    "recordId" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    "value" TEXT NOT NULL,
    "agentId" TEXT NOT NULL,
    "retiredAt" DATETIME,
    CONSTRAINT "conflict_sides_conflictId_fkey" FOREIGN KEY ("conflictId") REFERENCES "conflicts" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "conflict_sides_recordRowId_fkey" FOREIGN KEY ("recordRowId") REFERENCES "memory_records" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "idempotency_entries" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "agentId" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "requestHash" TEXT NOT NULL,
    "resultJson" TEXT NOT NULL,
    "operation" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "idempotency_entries_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "idempotency_entries_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "agents" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "search_docs" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "recordRowId" TEXT NOT NULL,
    "recordId" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    "scope" TEXT NOT NULL,
    "agentId" TEXT NOT NULL,
    "tokens" TEXT NOT NULL,
    "length" INTEGER NOT NULL,
    CONSTRAINT "search_docs_recordRowId_fkey" FOREIGN KEY ("recordRowId") REFERENCES "memory_records" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "search_docs_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "recall_cache_entries" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "queryHash" TEXT NOT NULL,
    "recordRowIds" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "invalidatedAt" DATETIME,
    CONSTRAINT "recall_cache_entries_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "deletion_ledger" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "recordId" TEXT NOT NULL,
    "rowIds" TEXT NOT NULL,
    "purged" BOOLEAN NOT NULL DEFAULT true,
    "deletedBy" TEXT NOT NULL,
    "reason" TEXT NOT NULL DEFAULT '',
    "deletedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "deletion_ledger_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "audit_events" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "actorType" TEXT NOT NULL,
    "actorId" TEXT NOT NULL,
    "actorName" TEXT NOT NULL DEFAULT '',
    "action" TEXT NOT NULL,
    "targetId" TEXT NOT NULL DEFAULT '',
    "detail" TEXT NOT NULL DEFAULT '{}',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "audit_events_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "reward_credits" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "recordId" TEXT NOT NULL,
    "authorAgentId" TEXT NOT NULL,
    "usedByAgentId" TEXT NOT NULL,
    "points" INTEGER NOT NULL DEFAULT 1,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "reward_credits_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "reward_accruals" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "address" TEXT NOT NULL,
    "periodStart" DATETIME NOT NULL,
    "periodEnd" DATETIME NOT NULL,
    "amount" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "model_usage" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "workspaceId" TEXT NOT NULL,
    "provider" TEXT NOT NULL DEFAULT 'openrouter',
    "generationId" TEXT NOT NULL,
    "reportedByAgentId" TEXT NOT NULL,
    "model" TEXT NOT NULL DEFAULT '',
    "reportedTokens" INTEGER NOT NULL DEFAULT 0,
    "reportedCostMicros" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "rejectedReason" TEXT NOT NULL DEFAULT '',
    "verifiedTokens" INTEGER NOT NULL DEFAULT 0,
    "verifiedCostMicros" INTEGER NOT NULL DEFAULT 0,
    "reportedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "verifiedAt" DATETIME,
    CONSTRAINT "model_usage_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "workspaces" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "users_walletProvenAddress_key" ON "users"("walletProvenAddress");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "spent_siwe_nonces_nonceHash_key" ON "spent_siwe_nonces"("nonceHash");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "spent_siwe_nonces_expiresAt_idx" ON "spent_siwe_nonces"("expiresAt");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "workspaces_slug_key" ON "workspaces"("slug");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "workspaces_ownerId_idx" ON "workspaces"("ownerId");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "agents_keyHash_key" ON "agents"("keyHash");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "agents_workspaceId_idx" ON "agents"("workspaceId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "agents_keyHash_idx" ON "agents"("keyHash");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "memory_records_workspaceId_isCurrent_deletedAt_idx" ON "memory_records"("workspaceId", "isCurrent", "deletedAt");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "memory_records_workspaceId_topic_idx" ON "memory_records"("workspaceId", "topic");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "memory_records_workspaceId_factKey_factContext_idx" ON "memory_records"("workspaceId", "factKey", "factContext");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "memory_records_workspaceId_contentHash_idx" ON "memory_records"("workspaceId", "contentHash");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "memory_records_agentId_idx" ON "memory_records"("agentId");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "memory_records_recordId_version_key" ON "memory_records"("recordId", "version");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "record_links_workspaceId_idx" ON "record_links"("workspaceId");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "record_links_fromRecordId_toRecordId_kind_key" ON "record_links"("fromRecordId", "toRecordId", "kind");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "merged_blocks_workspaceId_topic_idx" ON "merged_blocks"("workspaceId", "topic");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "merged_blocks_workspaceId_staleAt_idx" ON "merged_blocks"("workspaceId", "staleAt");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "merged_block_sources_recordId_idx" ON "merged_block_sources"("recordId");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "merged_block_sources_blockId_recordRowId_key" ON "merged_block_sources"("blockId", "recordRowId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "conflicts_workspaceId_status_idx" ON "conflicts"("workspaceId", "status");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "conflicts_workspaceId_scope_factKey_factContext_key" ON "conflicts"("workspaceId", "scope", "factKey", "factContext");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "conflict_sides_recordId_idx" ON "conflict_sides"("recordId");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "conflict_sides_conflictId_recordRowId_key" ON "conflict_sides"("conflictId", "recordRowId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "idempotency_entries_workspaceId_agentId_idx" ON "idempotency_entries"("workspaceId", "agentId");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "idempotency_entries_workspaceId_key_key" ON "idempotency_entries"("workspaceId", "key");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "search_docs_recordRowId_key" ON "search_docs"("recordRowId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "search_docs_workspaceId_scope_idx" ON "search_docs"("workspaceId", "scope");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "recall_cache_entries_workspaceId_invalidatedAt_idx" ON "recall_cache_entries"("workspaceId", "invalidatedAt");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "recall_cache_entries_workspaceId_queryHash_key" ON "recall_cache_entries"("workspaceId", "queryHash");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "deletion_ledger_workspaceId_deletedAt_idx" ON "deletion_ledger"("workspaceId", "deletedAt");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "deletion_ledger_recordId_idx" ON "deletion_ledger"("recordId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "audit_events_workspaceId_createdAt_idx" ON "audit_events"("workspaceId", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "reward_credits_recordId_key" ON "reward_credits"("recordId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "reward_credits_workspaceId_createdAt_idx" ON "reward_credits"("workspaceId", "createdAt");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "reward_credits_createdAt_idx" ON "reward_credits"("createdAt");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "reward_accruals_address_idx" ON "reward_accruals"("address");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "reward_accruals_periodStart_idx" ON "reward_accruals"("periodStart");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "reward_accruals_address_periodStart_key" ON "reward_accruals"("address", "periodStart");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "model_usage_workspaceId_verifiedAt_idx" ON "model_usage"("workspaceId", "verifiedAt");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "model_usage_status_reportedAt_idx" ON "model_usage"("status", "reportedAt");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "model_usage_provider_generationId_key" ON "model_usage"("provider", "generationId");

