import type { HardhatRuntimeEnvironment } from 'hardhat/types';

import { ethersOf } from './hre';

/**
 * The slice of OffcutRewards these scripts touch.
 *
 * Deliberately hand-written rather than imported from typechain-types/: those
 * are generated by `hardhat compile`, and a deploy script that stops working
 * because the generated directory is stale or absent is a script that fails on
 * the one morning it is needed. Everything below is read straight off
 * contracts/OffcutRewards.sol; if the contract changes shape, the ABI call
 * fails loudly at the first read-back, which is exactly when we want to know.
 */
export interface RewardsContract {
  getAddress(): Promise<string>;
  owner(): Promise<string>;
  pendingOwner(): Promise<string>;
  publisher(): Promise<string>;
  token(): Promise<string>;
  paused(): Promise<boolean>;
  rootIndex(): Promise<bigint>;
  merkleRoot(): Promise<string>;
  rootPublishedAt(): Promise<bigint>;
  totalClaimed(): Promise<bigint>;
  setToken(token: string): Promise<{ hash: string; wait(confirmations?: number): Promise<unknown> }>;
}

export async function attachRewards(
  hre: HardhatRuntimeEnvironment,
  address: string
): Promise<RewardsContract> {
  const eth = ethersOf(hre);
  const factory = await eth.getContractFactory('OffcutRewards');
  // With no key configured (status is read-only and needs none) the factory has
  // no runner and every call fails with "contract runner does not support
  // calling"; the provider is enough for reads, a signer is used when there is one.
  const signers = await eth.getSigners();
  const runner = signers[0] ?? eth.provider;
  return factory.attach(address).connect(runner) as unknown as RewardsContract;
}

/** A token read far enough to print a balance; every call is allowed to fail. */
export interface Erc20Readonly {
  decimals(): Promise<bigint>;
  symbol(): Promise<string>;
  balanceOf(account: string): Promise<bigint>;
}

export const ERC20_READ_ABI = [
  'function decimals() view returns (uint8)',
  'function symbol() view returns (string)',
  'function balanceOf(address) view returns (uint256)',
];
